services:
  abus.sh:
    build: abus.sh
    volumes:
      - type: bind
        source: ./abus.sh/dist/abus.sh/browser
        target: /data/abus.sh
      - type: bind
        source: ./secrets
        target: /data/secrets
      - type: bind
        source: ./config/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./config/nginx/conf.d
        target: /etc/nginx/conf.d
    environment:
      EDITOR: vim